import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { chromium } from 'playwright';
import { startDemo } from '../dist/demo.js';
import { readFixtures } from '../dist/config.js';
import { runSuite, readSavedPlan, providerOptions } from '../dist/runner.js';
import { decide } from '../dist/providers.js';
import { parseExplicit } from '../dist/plan.js';
import { observe, execute, disposeObservation } from '../dist/browser.js';
import { checkAssertion } from '../dist/assertions.js';
import { benchmark, scriptedDecision, faults } from './helpers.mjs';

test('known secrets in URL and control metadata never reach the decision provider',async()=>{
  const secret='private-route-and-attribute-value';const browser=await chromium.launch();
  try{
    const page=await browser.newPage();await page.route('https://metadata.test/**',route=>route.fulfill({contentType:'text/html',body:`<input aria-label="Name" role="${secret}" type="${secret}">`}));await page.goto(`https://metadata.test/${secret}?ignored=private-query`);
    const observation=await observe(page,[secret]);let payload='';const fetchImpl=async(_url,options)=>{if(!options?.body)return Response.json({data:{endpoints:[{pricing:{prompt:'0',completion:'0'}}]}});payload=options.body;return Response.json({answers:{target:{type:'choice',choice:observation.controls[0].id},navigation:{type:'choice',choice:'blocked'}},usage:{cost:0}});};
    await decide(observation,{action:'fill',target:'Name',value:'Public test',fixture:null},providerOptions({apiKey:'fake-test-key',fetchImpl}),new AbortController().signal);
    assert.ok(!payload.includes(secret),'Known secret escaped through URL/control metadata');assert.ok(!payload.includes('fingerprint'));assert.ok(!payload.includes('private-query'));await disposeObservation(observation);
  }finally{await browser.close();}
});

test('ten real browser flows pass healthy and detect all ten corresponding mutations',async()=>{const demo=await startDemo(0);const directory=await mkdtemp(join(tmpdir(),'jev-browser-'));try{const fixtures=readFixtures(await demo.writeFixtures(directory));const suite=await benchmark();const healthy=await runSuite({url:demo.url,plan:suite,fixtures,decide:scriptedDecision,outputDirectory:join(directory,'healthy'),beforeCase:async()=>demo.reset(),assertionTimeoutMs:600});assert.equal(healthy.verdict,'PASS',JSON.stringify(healthy.cases.map(c=>({name:c.name,verdict:c.verdict,reason:c.reason,checks:c.checks}))));assert.equal(healthy.cases.length,10);assert.equal(healthy.model.requests,0);const broken=await runSuite({url:demo.url,plan:suite,fixtures,decide:scriptedDecision,outputDirectory:false,beforeCase:async(index)=>demo.reset(faults[index]),assertionTimeoutMs:600});assert.deepEqual(broken.cases.map(c=>c.verdict),Array(10).fill('FAIL'),JSON.stringify(broken.cases));const saved=await readSavedPlan(join(directory,'healthy','plan.json'));const replay=await runSuite({url:demo.url,replay:saved,fixtures,decide:async()=>{throw Error('Unchanged replay should not call the model.');},outputDirectory:false,beforeCase:async()=>demo.reset(),assertionTimeoutMs:600});assert.equal(replay.verdict,'PASS',JSON.stringify(replay.cases));assert.equal(replay.model.plannerRequests,0);assert.equal(replay.model.jevRequests,0);assert.ok(replay.cases.every(c=>c.checks.length===suite.cases.find(t=>t.name===c.name).assertions.length));const report=await readFile(join(directory,'healthy','report.json'),'utf8');for(const secret of ['demo-password','demo@example.test','demo-signed-in'])assert.ok(!report.includes(secret));}finally{await demo.close();await rm(directory,{recursive:true,force:true});}});
test('stale DOM replacement, ambiguous scopes and substring entities cannot produce false proof',async()=>{const browser=await chromium.launch();try{const page=await browser.newPage();await page.goto('about:blank');await page.setContent('<button id="save">Save</button><script>window.calls=0;document.querySelector("button").onclick=()=>window.calls++;</script><ul><li><strong>Acme Beta</strong></li></ul>');const observation=await observe(page,[]);const control=observation.controls[0];await page.evaluate(()=>{const old=document.querySelector('button');const clone=old.cloneNode(true);clone.onclick=()=>window.calls++;old.replaceWith(clone);});await assert.rejects(execute(page,observation,control,{action:'click',target:'Save',value:null,fixture:null},null,new AbortController().signal,new Set(['null'])),/replaced|changed/);assert.equal(await page.evaluate(()=>window.calls),0);await disposeObservation(observation);const assertion={kind:'count',target:{by:'record',text:'Acme',role:null,within:null},expected:1};const check=await checkAssertion(page,assertion,new AbortController().signal,0);assert.equal(check.passed,false);assert.equal(check.observed,0);await assert.rejects(checkAssertion(page,{kind:'absent',target:{by:'text',text:'Archived',role:null,within:'record:Missing'},expected:false},new AbortController().signal,0),/scope/);}finally{await browser.close();}});
test('cancel during a browser wait closes the context and dispatches no subsequent action',async()=>{const demo=await startDemo(0);const directory=await mkdtemp(join(tmpdir(),'jev-cancel-'));try{const fixtures=readFixtures(await demo.writeFixtures(directory));const controller=new AbortController();let closed=false;const plan=parseExplicit('Case: Cancel\nAuth: @signed-in\nGoal: Cancel test\nStep: Wait for text "Never appears"\nStep: Click "New project"\nExpect: text "Done" is visible');const started=Date.now();const result=await runSuite({url:demo.url,plan,fixtures,decide:scriptedDecision,signal:controller.signal,outputDirectory:false,onProgress:event=>{if(event.type==='step')setTimeout(()=>controller.abort(),50);if(event.type==='context.closed')closed=true;}});assert.equal(result.verdict,'BLOCKED');assert.equal(result.canceled,true);assert.equal(result.cases[0].actions.length,0);assert.ok(closed);assert.ok(Date.now()-started<5000);}finally{await demo.close();await rm(directory,{recursive:true,force:true});}});
test('missing fixtures and provider errors do not mutate the app',async()=>{const demo=await startDemo(0);try{const source='Case: Login\nGoal: Sign in\nInput: Email = @missing.email\nInput: Password = @missing.password\nExpect: text "Welcome back" is visible';const result=await runSuite({url:demo.url,casesText:source,planner:'off',outputDirectory:false,decide:scriptedDecision});assert.equal(result.verdict,'BLOCKED');assert.equal(result.cases[0].actions.length,0);}finally{await demo.close();}});
test('a reused control whose entity context changes is blocked before clicking',async()=>{
  const browser=await chromium.launch();try{const page=await browser.newPage();await page.setContent('<ul><li><strong>Demo</strong><button>Archive</button></li></ul><script>window.calls=0;document.querySelector("button").onclick=()=>window.calls++;</script>');const snapshot=await observe(page,[]);await page.locator('strong').evaluate(element=>element.textContent='Other account');await assert.rejects(execute(page,snapshot,snapshot.controls[0],{action:'click',target:'Archive project Demo',value:null,fixture:null},null,new AbortController().signal,new Set(['null'])),/changed/);assert.equal(await page.evaluate(()=>window.calls),0);await disposeObservation(snapshot);}finally{await browser.close();}
});
