import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { parseExplicit, compileCases, planHash } from '../dist/plan.js';
import { decide } from '../dist/providers.js';
import { readFixtures, secretValues, sanitize, redact } from '../dist/config.js';
import { readSavedPlan, runSuite } from '../dist/runner.js';
import { validateSuite } from '../dist/types.js';
import { parseNumber } from '../dist/assertions.js';
import { benchmark, provider } from './helpers.mjs';

test('ten benchmark contracts preserve inputs, fixtures and persistence',async()=>{const suite=await benchmark();assert.equal(suite.cases.length,10);for(const c of suite.cases)assert.equal(c.blockedReason,null,c.name+': '+c.blockedReason);assert.equal(suite.cases[1].steps[1].fixture,'invalid.password');assert.equal(suite.cases[2].steps[1].value,'Acme');assert.equal(suite.cases[2].steps.at(-1).action,'reload');assert.equal(suite.cases[8].steps[1].value,'');assert.equal(suite.cases[4].assertions[0].target.within,'record:Demo');});
test('30 supported explicit cases parse without inventing expectations',()=>{const goals=['Create project named "A \\"quote\\""','Rename project "Demo" to "Acme"','Archive project "Demo"','Filter projects to Archived','Set "Theme" to "Dark"','Check "Enable notifications"','Uncheck "Enable notifications"','Search projects for "Demo"','Create a project with an empty name','Other explicit journey'];for(let i=0;i<30;i++){const index=i%goals.length;const source=`Case: case ${i}\nGoal: ${goals[index]}\n${index===8?'Input: Project name = ""\n':index===9?'Step: Click "Continue"\n':''}Expect: text "Expected ${i}" is visible`;const c=parseExplicit(source).cases[0];assert.equal(c.blockedReason,null,source+'\n'+c.blockedReason);assert.equal(c.assertions[0].target.text,`Expected ${i}`);}});
test('unsupported, ambiguous and credential-literal cases stay blocked',()=>{for(const source of ['Goal: solve CAPTCHA\nExpect: text "Done" is visible','Goal: Create project named "X"','Goal: Sign in\nInput: Password = "secret-literal"\nExpect: text "Welcome" is visible','Goal: Create project named "X"\nGoal: Create project named "Y"\nExpect: text "Done" is visible'])assert.ok(parseExplicit('Case: Bad\n'+source).cases[0].blockedReason);assert.throws(()=>parseExplicit(''),/Provide/);const good=parseExplicit('Case: Good\nGoal: Check "Enable notifications"\nExpect: checkbox "Enable notifications" is checked');good.cases[0].assertions=[];assert.throws(()=>validateSuite(good),/expectations/);});
test('strict numeric parsing cannot accept a partial amount',()=>{assert.equal(parseNumber('$1,234.50'),1234.5);assert.equal(parseNumber('5 projects'),null);assert.equal(parseNumber('NaN'),null);});
test('Jev transport uses Decisions, verifies both heads and never sends fixture values',async()=>{const snapshot={url:'http://app.test/',text:'Settings',controls:[{id:'e1',tag:'button',role:'button',label:'Settings',context:'Account',type:'',disabled:false,checked:null,options:[],fingerprint:'private internal metadata'},{id:'e2',tag:'button',role:'button',label:'Buy now',context:'Product',type:'',disabled:false,checked:null,options:[],fingerprint:'unsafe'}]};let call;const p=provider({fetchImpl:async(url,options)=>{call={url,options,payload:JSON.parse(options.body)};return Response.json({model:'typesafe/jev-1.13-test',answers:{target:{type:'choice',choice:'e1'},navigation:{type:'choice',choice:'blocked'}},usage:{cost:0.00002}});}});const result=await decide(snapshot,{action:'click',target:'Settings',value:null,fixture:null},p,new AbortController().signal);assert.equal(call.url,'https://openrouter.ai/api/alpha/decisions');assert.equal(result.target,'e1');assert.ok(!Object.hasOwn(call.payload.questions.navigation.criteria,'e2'));assert.ok(!call.options.body.includes('private internal'));assert.ok(!call.options.body.includes('unit-test-key'));assert.equal(p.stats.jevRequests,1);assert.equal(p.stats.cost,0.00002);for(const answers of [{target:{type:'choice',choice:'invented'},navigation:{type:'choice',choice:'blocked'}},{target:{type:'choice',choice:'e1'}},{target:{type:'score',choice:'e1'},navigation:{type:'choice',choice:'blocked'}}])await assert.rejects(decide(snapshot,{action:'click',target:'Settings',value:null,fixture:null},provider({fetchImpl:async()=>Response.json({answers})}),new AbortController().signal),/invalid|incompatible/);});
test('budget, request cap, provider failure and cancellation cannot turn green',async()=>{let calls=0;const snapshot={url:'http://app.test/',text:'',controls:[]};const step={action:'click',target:'Continue',value:null,fixture:null};const fetchImpl=async()=>{calls++;return Response.json({error:'sensitive-provider-detail'}, {status:429});};await assert.rejects(decide(snapshot,step,provider({maxCost:0.000000001,fetchImpl}),new AbortController().signal),/budget/);assert.equal(calls,0);await assert.rejects(decide(snapshot,step,provider({maxRequests:0,fetchImpl}),new AbortController().signal),/limit/);assert.equal(calls,0);await assert.rejects(decide(snapshot,step,provider({fetchImpl}),new AbortController().signal),/HTTP 429/);const controller=new AbortController();controller.abort();await assert.rejects(decide(snapshot,step,provider({fetchImpl}),controller.signal));assert.equal(calls,1);});
test('Jev reserves a bounded completion even when provider usage is unavailable',async()=>{const snapshot={url:'http://app.test/',text:'',controls:[{id:'e1',tag:'button',role:'button',label:'Continue',context:'',type:'',disabled:false,checked:null,options:[],fingerprint:'x'}]},step={action:'click',target:'Continue',value:null,fixture:null};let calls=0;const prices=new Map([['typesafe/jev-1.13',{prompt:0,completion:.001}]]);await assert.rejects(decide(snapshot,step,provider({maxCost:.25,prices,fetchImpl:async()=>{calls++;return Response.json({answers:{target:{type:'choice',choice:'e1'},navigation:{type:'choice',choice:'blocked'}}});}}),new AbortController().signal),/budget/);assert.equal(calls,0);const p=provider({maxCost:1,prices,fetchImpl:async()=>Response.json({answers:{target:{type:'choice',choice:'e1'},navigation:{type:'choice',choice:'blocked'}}})});await decide(snapshot,step,p,new AbortController().signal);assert.equal(p.stats.cost,.256);});
test('a read-only decision transport timeout retries once within request and cost budgets',async()=>{const snapshot={url:'http://app.test/',text:'',controls:[{id:'e1',tag:'button',role:'button',label:'Continue',context:'',type:'',disabled:false,checked:null,options:[],fingerprint:'x'}]},step={action:'click',target:'Continue',value:null,fixture:null};let calls=0;const p=provider({fetchImpl:async()=>{calls++;if(calls===1)throw Error('network');return Response.json({model:'typesafe/jev-1.13',answers:{target:{type:'choice',choice:'e1'},navigation:{type:'choice',choice:'blocked'}},usage:{cost:.00001}});}});assert.deepEqual(await decide(snapshot,step,p,new AbortController().signal),{target:'e1',navigation:'blocked'});assert.equal(calls,2);assert.equal(p.stats.requests,2);assert.ok(p.stats.cost>.00001);calls=0;await assert.rejects(decide(snapshot,step,provider({maxRequests:1,fetchImpl:async()=>{calls++;throw Error('network');}}),new AbortController().signal),/failed/);assert.equal(calls,1);});
test('planner rejects changed expectations, input targets, fixtures and literals before browser launch',async()=>{
  const original='Case: Persist\nAuth: @signed-in\nGoal: Create project named "Acme"\nExpect: project named "Acme" exists exactly once after reload';const plan=parseExplicit(original);
  const fetchFor=plan=>async()=>Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(plan)}}],usage:{cost:0.0001}});
  const fixtures={inputs:{},auth:{'signed-in':{storageState:'not-read-at-compile'}}};
  const accepted=await compileCases(original,'on',fixtures,provider({fetchImpl:fetchFor(plan)}),new AbortController().signal);assert.deepEqual(accepted,plan);
  for(const change of [p=>p.cases[0].steps[1].target='Search projects',p=>p.cases[0].steps[1].value='Acme Beta',p=>p.cases[0].assertions[0].expected=2,p=>{p.cases[0].steps[1].value=null;p.cases[0].steps[1].fixture='different';},p=>p.cases[0].steps.pop()]){
    const altered=structuredClone(plan);change(altered);await assert.rejects(compileCases(original,'on',fixtures,provider({fetchImpl:fetchFor(altered)}),new AbortController().signal),/Planner/);
  }
  const negative='Case: Invalid password\nGoal: Sign in with invalid credentials\nInput: Email = @valid.email\nInput: Password = @invalid.password\nExpect: text "Invalid credentials" is visible';const swapped=parseExplicit(negative);swapped.cases[0].steps[0].target='Password';swapped.cases[0].steps[1].target='Email';
  await assert.rejects(compileCases(negative,'on',fixtures,provider({fetchImpl:fetchFor(swapped)}),new AbortController().signal),/Planner/);
});
test('fixtures and auth values redact locally, escaped secrets cannot evade plan guard',async()=>{const directory=await mkdtemp(join(tmpdir(),'jev-fixtures-'));try{await writeFile(join(directory,'auth.json'),JSON.stringify({cookies:[{value:'private-session-value'}],origins:[{localStorage:[{value:'private-local-token'}]}]}));await writeFile(join(directory,'fixtures.json'),JSON.stringify({inputs:{password:{env:'TEST_PASSWORD'}},auth:{user:{storageState:'auth.json'}}}));const fixtures=readFixtures(join(directory,'fixtures.json'),{TEST_PASSWORD:'quoted"password'});const secrets=secretValues(fixtures,{});assert.ok(secrets.includes('private-session-value'));assert.equal(sanitize({message:'private-local-token and quoted"password'},secrets).message,'[REDACTED] and [REDACTED]');const plan=parseExplicit('Case: Secret\nGoal: Create project named "quoted\\"password"\nExpect: text "Done" is visible');const result=await runSuite({url:'http://127.0.0.1:1',plan,fixtures,outputDirectory:false});assert.equal(result.verdict,'BLOCKED');assert.equal(result.cases[0].actions.length,0);assert.ok(!JSON.stringify(result).includes('quoted\\"password'));}finally{await rm(directory,{recursive:true,force:true});}});
test('saved plan integrity and incomplete plans are rejected',async()=>{const directory=await mkdtemp(join(tmpdir(),'jev-plan-'));try{const plan=parseExplicit('Case: One\nGoal: Check "Enable notifications"\nExpect: checkbox "Enable notifications" is checked');const location=join(directory,'plan.json');await writeFile(location,JSON.stringify({version:1,plan,hash:planHash(plan),flows:[null]}));assert.equal((await readSavedPlan(location)).plan.cases.length,1);plan.cases[0].assertions[0].expected=false;await writeFile(location,JSON.stringify({version:1,plan,hash:'old-hash',flows:[null]}));await assert.rejects(readSavedPlan(location),/integrity/);}finally{await rm(directory,{recursive:true,force:true});}});
test('auth setup is owned by the caller and cannot be invented or substituted by a planner',async()=>{
  const source='Case: Sign in\nSign in using Email @valid.email and Password @valid.password.\nExpect: text "Welcome back" is visible';const raw=parseExplicit('Case: Sign in\nGoal: Sign in\nInput: Email = @valid.email\nInput: Password = @valid.password\nExpect: text "Welcome back" is visible');raw.cases[0].source=source;raw.cases[0].auth='signed-in';
  const fixtures={inputs:{'valid.email':{value:'fake-email'},'valid.password':{value:'fake-password'}},auth:{'signed-in':{storageState:'not-read-at-compile'}}};const compiled=await compileCases(source,'on',fixtures,provider({fetchImpl:async()=>Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(raw)}}],usage:{cost:0}})}),new AbortController().signal);assert.equal(compiled.cases[0].auth,null);assert.equal(compiled.cases[0].steps[0].fixture,'valid.email');
});
test('truncation cannot expose the tail of a known secret and numeric commas must be grouped correctly',()=>{
  const secret='private-fixture-token-that-is-longer-than-the-label';assert.equal(redact('Account '+secret.slice(0,20),[secret]),'Account [REDACTED]');assert.equal(parseNumber('1,2'),null);assert.equal(parseNumber('1 2'),null);assert.equal(parseNumber('12,34.50'),null);assert.equal(parseNumber('-$1,234.50'),-1234.5);
});
