import React, {useEffect, useState} from 'react';
import {SafeAreaView, View, Text, TextInput, Pressable, ScrollView, StyleSheet, Platform, Keyboard, Switch} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {StatusBar} from 'expo-status-bar';

const products=[{name:'Desk Lamp',price:36,icon:'☀',category:'Home'},{name:'AirPods',price:120,icon:'♫',category:'Audio'},{name:'Notebook',price:8,icon:'▤',category:'Office'}];
const base={signedIn:false,cart:{},notifications:false};
const Button=({name,onPress,subtle=false})=><Pressable accessibilityRole="button" accessibilityLabel={name} testID={name.replaceAll(' ','-')} onPress={onPress} style={[s.button,subtle&&s.subtle]}><Text style={[s.buttonText,subtle&&{color:'#ededec'}]}>{name}</Text></Pressable>;

export default function App(){
  const [state,setState]=useState(base),[ready,setReady]=useState(false),[screen,setScreen]=useState('catalog'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState(''),[product,setProduct]=useState(products[0]),[fault,setFault]=useState('healthy');
  useEffect(()=>{(async()=>{
    let config={id:'manual',fault:'healthy'};
    try {config=await (await fetch(`http://${Platform.OS==='android'?'10.0.2.2':'127.0.0.1'}:8089/config?platform=${Platform.OS}`)).json();}catch{}
    const saved=JSON.parse(await AsyncStorage.getItem('jev-lab')||'null');
    setFault(config.fault);
    setState(saved?.id===config.id ? {...saved.state,cart:config.fault==='lost-persistence'?{}:saved.state.cart} : base);
    await AsyncStorage.setItem('jev-lab-id',config.id);setReady(true);
  })();},[]);
  useEffect(()=>{if(ready)(async()=>{const id=await AsyncStorage.getItem('jev-lab-id');await AsyncStorage.setItem('jev-lab',JSON.stringify({id,state}));})();},[state,ready]);
  function signIn(){Keyboard.dismiss();if(email==='demo@example.test'&&password==='correct-horse'||fault==='invalid-login'){setState({...state,signedIn:true});setError('');}else setError('Invalid credentials');}
  function add(){setState({...state,cart:{...state.cart,[product.name]:(state.cart[product.name]||0)+1}});setScreen('cart');}
  const listed=fault==='wrong-filter'&&query?products:products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));
  const total=products.reduce((n,p)=>n+p.price*(state.cart[p.name]||0),0)+(fault==='wrong-total'?5:0);
  return <SafeAreaView style={s.root}><StatusBar style="light"/><View style={s.page}>
    <View style={s.brand}><Text style={s.logo}>◆</Text><Text style={s.brandText}>JEV SHOP</Text><Text style={s.tag}>NATIVE LAB</Text></View>
    {!ready?<Text style={s.title}>Loading</Text>:!state.signedIn?<View accessibilityLabel="Sign in screen" testID="sign-in-screen"><Text style={s.title}>Welcome back.</Text><Text style={s.caption}>Your next great find starts here.</Text><Text style={s.label}>Email</Text><TextInput accessibilityLabel="Email" testID="email" style={s.input} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address"/><Text style={s.label}>Password</Text><TextInput accessibilityLabel="Password" testID="password" style={s.input} value={password} onChangeText={setPassword} secureTextEntry/><Button name="Sign in" onPress={signIn}/>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}</View>:<>
    <View style={s.tabs}><Button name="Catalog" subtle onPress={()=>setScreen('catalog')}/><Button name="Cart" subtle onPress={()=>setScreen('cart')}/><Button name="Settings" subtle onPress={()=>setScreen('settings')}/></View>
    {screen==='catalog'?<View accessibilityLabel="Catalog screen" testID="catalog-screen"><Text style={s.title}>Find your favorite.</Text><Text style={s.caption}>Thoughtful essentials. Everyday prices.</Text><TextInput accessibilityLabel="Search products" testID="search-products" style={s.input} placeholder="Search products" placeholderTextColor="#858585" value={query} onChangeText={setQuery} returnKeyType="done" onSubmitEditing={()=>Keyboard.dismiss()}/><Button name="Dismiss keyboard" subtle onPress={()=>Keyboard.dismiss()}/><View accessibilityLabel="Products" testID="products">{listed.map(p=><View key={p.name} style={s.card}><Text style={s.productIcon}>{p.icon}</Text><View style={{flex:1}}><Text style={s.product}>{p.name}</Text><Text style={s.caption}>{p.category} · ${p.price.toFixed(2)}</Text></View><Button name={`Open ${p.name}`} onPress={()=>{Keyboard.dismiss();setProduct(p);setScreen('detail');}}/></View>)}{!listed.length?<Text style={s.caption}>No products found</Text>:null}</View></View>:null}
    {screen==='detail'?<View accessibilityLabel="Product detail" testID="product-detail"><Text style={s.heroIcon}>{product.icon}</Text><Text style={s.title}>{product.name}</Text><Text style={s.caption}>{product.category} collection</Text><Text style={s.price}>${product.price.toFixed(2)}</Text><Button name="Add to cart" onPress={add}/><Button name="Back to catalog" subtle onPress={()=>setScreen('catalog')}/></View>:null}
    {screen==='cart'?<View accessibilityLabel="Cart screen" testID="cart-screen"><Text style={s.title}>Your cart.</Text><Text style={s.caption}>Good choices, all in one place.</Text><View accessibilityLabel="Cart items" testID="cart-items">{products.filter(p=>state.cart[p.name]).map(p=><View key={p.name} style={s.cartCard}><Text style={s.product}>{p.name}</Text><Text style={s.caption}>Quantity: {state.cart[p.name]}</Text><View style={s.cartButtons}><Button name={`Increase ${p.name} quantity`} onPress={()=>setState({...state,cart:{...state.cart,[p.name]:state.cart[p.name]+1}})}/><Button name={`Remove ${p.name}`} subtle onPress={()=>{if(fault!=='ineffective-removal'){const cart={...state.cart};delete cart[p.name];setState({...state,cart});}}}/></View></View>)}</View>{!Object.values(state.cart).some(Boolean)?<Text style={s.empty}>Your cart is empty</Text>:null}<View style={s.total}><Text style={s.product}>Total</Text><Text accessibilityLabel="Cart total" accessibilityValue={{text:total.toFixed(2)}} testID="cart-total" style={s.price}>{total.toFixed(2)}</Text></View><Button name="Continue shopping" subtle onPress={()=>setScreen('catalog')}/></View>:null}
    {screen==='settings'?<View><Text style={s.title}>Make it yours.</Text><Text style={s.caption}>Simple settings, instant updates.</Text><View style={s.card}><Text style={s.product}>Notifications</Text><Switch accessibilityLabel="Notifications" testID="notifications" value={state.notifications} onValueChange={notifications=>setState({...state,notifications})}/></View><ScrollView accessibilityLabel="Settings list" style={{height:320}}><Text style={s.caption}>{Array.from({length:15},(_,i)=>`Preference ${i+1}\n`).join('\n')}</Text><Text style={s.caption}>End of preferences</Text></ScrollView><Button name="Sign out" subtle onPress={()=>{setState({...state,signedIn:false});setEmail('');setPassword('');setScreen('catalog');}}/></View>:null}
    </>}
    <Text style={s.footer}>DESIGNED TO BE TESTED.</Text>
  </View></SafeAreaView>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#101215'},page:{flex:1,padding:22},brand:{flexDirection:'row',alignItems:'center',gap:8,marginTop:18,marginBottom:24},logo:{color:'#ff773e',fontSize:24},brandText:{color:'#f4f4ef',fontSize:20,fontWeight:'900',letterSpacing:2},tag:{color:'#858589',fontSize:10,letterSpacing:1,marginLeft:'auto'},title:{color:'#f4f4ef',fontSize:32,fontWeight:'800',letterSpacing:-1,marginBottom:9},caption:{color:'#aaaab0',fontSize:14,lineHeight:22,marginBottom:10},label:{color:'#dddde1',fontSize:13,marginTop:15,marginBottom:8},input:{borderColor:'#393c43',borderWidth:1,borderRadius:12,padding:14,fontSize:16,color:'#f4f4ef',backgroundColor:'#1b1e24',marginBottom:10},button:{backgroundColor:'#ff773e',paddingVertical:13,paddingHorizontal:13,borderRadius:10,marginVertical:5},buttonText:{color:'#161514',fontWeight:'700',fontSize:13},subtle:{backgroundColor:'#252930'},tabs:{flexDirection:'row',gap:10,marginBottom:18},card:{flexDirection:'row',alignItems:'center',gap:12,padding:14,backgroundColor:'#1b1e24',borderColor:'#30333a',borderWidth:1,borderRadius:16,marginVertical:7},productIcon:{fontSize:34,color:'#ffad72',width:36},product:{fontSize:17,color:'#f4f4ef',fontWeight:'700'},heroIcon:{fontSize:100,color:'#ffad72',alignSelf:'center',marginVertical:30},price:{color:'#ffad72',fontSize:28,fontWeight:'800',marginVertical:15},cartCard:{padding:18,backgroundColor:'#1b1e24',borderRadius:16,marginVertical:8},cartButtons:{flexDirection:'row',flexWrap:'wrap',gap:8},total:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderTopWidth:1,borderTopColor:'#393c43',marginTop:12},empty:{color:'#dcdce0',fontSize:18,marginVertical:24},error:{color:'#ff8686',marginTop:14,fontSize:16},footer:{color:'#62656d',letterSpacing:2,fontSize:10,marginTop:'auto',alignSelf:'center',paddingTop:15}});
