import { writeFile, chmod } from 'node:fs/promises';
import { join } from 'node:path';
import { planHash } from './plan.js';
import type { SuiteResult } from './types.js';

const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!);
export async function writeReport(result: SuiteResult, directory: string): Promise<void> {
  await writeFile(join(directory, 'report.json'), JSON.stringify(result, null, 2), { mode: 0o600 });
  await writeFile(join(directory, 'plan.json'), JSON.stringify({ version: 1, plan: result.plan, hash: planHash(result.plan), flows: result.cases.map(test => test.verdict === 'PASS' ? test.flow : null) }, null, 2), { mode: 0o600 });
  const cases = result.cases.map(test => `<article><div class="case"><h2>${escape(test.name)}</h2><strong class="${test.verdict.toLowerCase()}">${test.verdict}</strong></div><p>${escape(test.goal)}</p><p>${escape(test.reason)}</p><table><thead><tr><th>Expectation</th><th>Expected</th><th>Observed</th><th>Result</th></tr></thead><tbody>${test.checks.map(check => `<tr><td>${escape(check.assertion.kind)} ${escape(check.assertion.target?.text ?? 'URL')}</td><td>${escape(check.assertion.expected)}</td><td>${escape(check.observed === null ? 'Not observed' : check.observed)}</td><td>${check.passed ? 'PASS' : 'FAIL'}</td></tr>`).join('')}</tbody></table><details><summary>Actions · ${(test.durationMs / 1000).toFixed(1)}s</summary><ol>${test.actions.map(action => `<li>${escape(action.action)} ${escape(action.target)}${action.replay ? ' · replay' : ''}</li>`).join('')}</ol></details>${test.screenshot ? `<img alt="Masked final state for ${escape(test.name)}" src="${escape(test.screenshot)}">` : ''}</article>`).join('');
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src 'self' data:"><title>jev-e2e · ${result.verdict}</title><style>body{font:16px/1.6 system-ui;background:#fafaf9;color:#202020;margin:0;padding:36px}main{max-width:1040px;margin:auto}header,article{background:white;border:1px solid #e8e8e5;border-radius:14px;padding:28px;margin:20px 0}.case{display:flex;align-items:center;justify-content:space-between;gap:20px}h1,h2{line-height:1.2}small{color:#626262}.pass{color:#166534}.fail{color:#b91c1c}.blocked{color:#92400e}table{width:100%;border-collapse:collapse;text-align:left;overflow-wrap:anywhere}td,th{padding:10px;border-bottom:1px solid #e8e8e5}img{display:block;max-width:100%;border:1px solid #e8e8e5;border-radius:8px;margin-top:20px}@media(max-width:600px){body{padding:10px}article,header{padding:16px}table{font-size:13px}.case{align-items:flex-start}}</style></head><body><main><header><small>JEV-E2E / CHECKED EVIDENCE</small><h1 class="${result.verdict.toLowerCase()}">${result.verdict}</h1><p>${escape(result.url)}</p><p>${result.cases.length} cases · ${(result.durationMs / 1000).toFixed(1)}s · ${result.model.requests} model requests · $${result.model.cost.toFixed(6)}</p><small>${escape(result.startedAt)} · ${escape(result.model.models.join(', ') || 'No model request')}</small></header>${cases}</main></body></html>`;
  await writeFile(join(directory, 'report.html'), html, { mode: 0o600 });
  await Promise.all(['report.json', 'plan.json', 'report.html'].map(name => chmod(join(directory, name), 0o600)));
}
