import { writeFile, chmod } from 'node:fs/promises';
import { join } from 'node:path';
import { savedHash } from './runner.js';
import type { SuiteResult } from './types.js';

const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!);
export async function writeReport(result: SuiteResult, directory: string): Promise<void> {
  await writeFile(join(directory, 'report.json'), JSON.stringify(result, null, 2), { mode: 0o600 });
  const flows = result.cases.map(test => test.verdict === 'PASS' ? test.flow : null);
  await writeFile(join(directory, 'plan.json'), JSON.stringify({ version: result.version, plan: result.plan, hash: savedHash(result.plan, result.target, flows), flows, ...(result.target ? { target: result.target } : {}) }, null, 2), { mode: 0o600 });
  const cases = result.cases.map((test, index) => {
    const remainingChecks = [...test.checks];
    const rows = result.plan.cases[index].assertions.map(assertion => {
      const matched = remainingChecks.findIndex(check => JSON.stringify(check.assertion) === JSON.stringify(assertion));
      const check = matched < 0 ? undefined : remainingChecks.splice(matched, 1)[0];
      return `<tr><td>${assertion.afterStep !== undefined ? `After step ${assertion.afterStep + 1}: ` : ''}${escape(assertion.kind)} ${escape(assertion.target?.text ?? 'URL')}</td><td>${escape(assertion.expected)}</td><td>${escape(check?.observed ?? 'Not observed')}</td><td>${check ? check.passed ? 'PASS' : 'FAIL' : 'NOT CHECKED'}${check?.reason ? `<small>${escape(check.reason)}</small>` : ''}</td></tr>`;
    }).join('');
    return `<article><div class="case"><h2>${escape(test.name)}</h2><strong class="${test.verdict.toLowerCase()}">${test.verdict}</strong></div><p>${escape(test.goal)}</p><p>${escape(test.reason)}</p>${test.evidenceNotes?.map(note => `<p><small>${escape(note)}</small></p>`).join('') ?? ''}<table><thead><tr><th>Expectation</th><th>Expected</th><th>Observed</th><th>Result</th></tr></thead><tbody>${rows}</tbody></table><details><summary>Actions · ${(test.durationMs / 1000).toFixed(1)}s</summary><ol>${test.actions.map(action => `<li>Step ${action.step + 1}: ${escape(action.action)} ${escape(action.target)}${action.replay ? ' · replay' : ''}${action.outcome ? ` · ${escape(action.outcome)}` : ''}</li>`).join('')}</ol></details>${test.video ? `<video class="phone" controls preload="metadata" src="${escape(test.video)}"></video><p><small>Local opt-in recording; credential-entry segment excluded. ${escape(test.videoMetadata ? JSON.stringify(test.videoMetadata) : '')}</small></p>` : ''}${test.screenshot ? `<img class="${result.version === 2 ? 'phone' : ''}" alt="Eligible final state for ${escape(test.name)}" src="${escape(test.screenshot)}">` : ''}</article>`;
  }).join('');
  const metadata = result.versions ? `<details><summary>Environment and full-run timings</summary><pre>${escape(JSON.stringify({ versions: result.versions, timingsMs: result.timings }, null, 2))}</pre></details>` : '';
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src 'self' data:; media-src 'self'"><title>jev-e2e · ${result.verdict}</title><style>body{font:16px/1.6 system-ui;background:#fafaf9;color:#202020;margin:0;padding:36px}main{max-width:1040px;margin:auto}header,article{background:white;border:1px solid #e8e8e5;border-radius:14px;padding:28px;margin:20px 0}.case{display:flex;align-items:center;justify-content:space-between;gap:20px}h1,h2{line-height:1.2}small{color:#626262;display:block}.pass{color:#166534}.fail{color:#b91c1c}.blocked{color:#92400e}table{width:100%;border-collapse:collapse;text-align:left;overflow-wrap:anywhere}td,th{padding:10px;border-bottom:1px solid #e8e8e5}img,video{display:block;max-width:100%;border:1px solid #e8e8e5;border-radius:12px;margin:20px auto}.phone{width:min(100%,430px);max-height:800px;object-fit:contain;background:#101215}pre{overflow:auto;font-size:12px}@media(max-width:600px){body{padding:10px}article,header{padding:16px}table{font-size:13px}.case{align-items:flex-start}}</style></head><body><main><header><small>JEV-E2E / CHECKED EVIDENCE</small><h1 class="${result.verdict.toLowerCase()}">${result.verdict}</h1><p>${escape(result.url)}${result.target ? ` · ${escape(result.target.platform.toUpperCase())} · ${escape(result.target.device)}` : ''}</p><p>${result.cases.length} cases · ${(result.durationMs / 1000).toFixed(1)}s · ${result.model.requests} model requests · $${result.model.cost.toFixed(6)}</p><small>${escape(result.startedAt)} · ${escape(result.model.models.join(', ') || 'No model request')}</small>${metadata}</header>${cases}</main></body></html>`;
  await writeFile(join(directory, 'report.html'), html, { mode: 0o600 });
  await Promise.all(['report.json', 'plan.json', 'report.html'].map(name => chmod(join(directory, name), 0o600)));
}
